# Generated by Django 3.1.2 on 2020-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='contactNo',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='emailId',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='groupName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_Booked',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='upiId',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='artist',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=100),
        ),
    ]
