# Generated by Django 3.1.2 on 2020-11-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201126_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_bio',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
