# Generated by Django 3.1.2 on 2020-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201126_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_category',
            field=models.CharField(max_length=100),
        ),
    ]
